version: "3.1"
services:
  db:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED:true
      - DOCKER_INFLUXDB_INIT_USERNAME: admin
      - DOCKER_INFLUXDB_INIT_PASSWORD: admin
      - DOCKER_INFLUXDB_INIT_ORG: mnofresno
      - DOCKER_INFLUXDB_INIT_BUCKET: iot
    ports:
      - 8083:8083
      - 8086:8086
  api:
    image: mnofresno/iot-api:2.0
    build:
      context: ./api
    ports:
      - 1387:1387
    environment:
      PORT: 1387
  dashboard:
    image: grafana/grafana
    ports:
      - 3000:3000
