version: "3.1"
services:
  db:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED:true
    ports:
      - 8083:8083
      - 8086:8086
  api:
    image: mnofresno/iot-api:2.0
    ports:
      - 1337:1337
  dashboard:
    image: grafana/grafana
    ports:
      - 3000:3000
